### ISSUE TITLE
How do you select multiple elements ?

### ISSUE THREAD

**Issue by maxenceC** [h2non/domlight#2]
One of the feature from this fork is : 

> multiple elements spotlight

But in the doc, there's no example, I tried using an array of selectors : 

Domlight([document.querySelector('#my-element'), document.querySelector('#my-2-element')], options)

And I tried using [ jQuery multiple selector](https://api.jquery.com/multiple-selector/), both without success.

How should we use multiple elements spotlight ? Could you add it to the doc

**Comment by h2non** [comment]
Multiple selectors are not supported.

**Comment by maxenceC** [comment]
Ok, thank you for your answer !
